spring:
  application:
    name: iam
  profiles:
    # The commented value for `active` can be replaced with valid Spring profiles to load.
    # Otherwise, it will be filled in by maven when building the JAR file
    # Either way, it can be overridden by `--spring.profiles.active` value passed in the commandline or `-Dspring.profiles.active` set in `JAVA_OPTS`
    active: #spring.profiles.active#
    group:
      dev:
        - dev
        - api-docs
        # Uncomment to activate TLS for the dev profile
        #- tls

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    operationsSorter: method
    path: /swagger-ui/index.html

application:
  clientApp:
    name: iam


server:
  servlet:
    session:
      cookie:
        http-only: true
