logging:
  level:
    ROOT: DEBUG
    vn.fpt.sims.iam: DEBUG

spring:
  devtools:
    restart:
      enabled: true
      additional-exclude: static/**
    livereload:
      enabled: false # we use Webpack dev server + BrowserSync for livereload
  jackson:
    serialization:
      indent-output: true

server:
  port: 9001

application:
  cache: # Cache configuration
    redis: # Redis configuration
      expiration: 3600 # By default objects stay 1 hour (in seconds) in the cache
      server: redis://${REDIS_HOST}:${REDIS_PORT}
      cluster: false
  cors:
    allowed-origins: 'http://dev-sims.fpt.vn/, https://dev-sims.fpt.vn/'
    allowed-methods: '*'
    allowed-headers: '*'
    exposed-headers: 'Authorization,Link,X-Total-Count,X-${application.clientApp.name}-alert,X-${application.clientApp.name}-error,X-${application.clientApp.name}-params'
    allow-credentials: true
    max-age: 1800
  http:
    proxy:
      host: ${PROXY_HOST}
      port: ${PROXY_PORT}

keycloak:
  realm: ${KEYCLOAK_REALM}
  auth-server-url: ${KEYCLOAK_AUTH_URL}
  ssl-required: external
  resource: ${KEYCLOAK_ADMIN_CLIENT_ID}
  credentials:
    secret: ${KEYCLOAK_ADMIN_CLIENT_SECRET}
    login-app-id: ${KEYCLOAK_CLIENT_ID}
    login-app-secret: ${KEYCLOAK_CLIENT_SECRET}
  use-resource-role-mappings: true
